# Generated by Django 3.2.4 on 2021-06-26 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên sản phẩm')),
                ('price', models.IntegerField(verbose_name='Giá')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Ảnh')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.category', verbose_name='Loại')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
                ('ordered', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
                ('shipping', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField()),
                ('products', models.ManyToManyField(to='coffee_shop.OrderProduct')),
            ],
        ),
    ]
