# Generated by Django 3.2.4 on 2021-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'CÀ PHÊ'), ('T', 'TRÀ TRÁI CÂY - TRÀ SỮA'), ('S', 'SMOOTHIE - ĐÁ XAY'), ('A', 'ĐỒ ĂN VẶT'), ('Q', 'Con Chó')], max_length=1, verbose_name='Loại'),
        ),
    ]
