# Generated by Django 3.2.4 on 2021-06-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Mô tả')),
                ('price', models.IntegerField(verbose_name='Giá')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên loại'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.category', verbose_name='Loại'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(to='coffee_shop.Option', verbose_name='Tùy chọn'),
        ),
    ]
