# Generated by Django 3.2.4 on 2021-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0004_auto_20210626_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='coffee_shop.Option', verbose_name='Tùy chọn'),
        ),
    ]
