# Generated by Django 3.2.4 on 2021-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0006_order_cancel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Topping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='topping',
            field=models.ManyToManyField(blank=True, to='coffee_shop.Topping'),
        ),
        migrations.AddField(
            model_name='product',
            name='topping',
            field=models.ManyToManyField(blank=True, to='coffee_shop.Topping', verbose_name='Topping'),
        ),
    ]
