# Generated by Django 3.2.4 on 2021-06-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0009_auto_20210628_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên loại'),
        ),
    ]
