# Generated by Django 3.2.4 on 2021-07-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0015_alter_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
    ]
