# Generated by Django 3.2.4 on 2021-07-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0017_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
