# Generated by Django 3.2.4 on 2021-07-05 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0018_auto_20210705_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 3, 36, 2, 281417, tzinfo=utc)),
        ),
    ]
