# Generated by Django 3.2.4 on 2021-07-05 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0019_alter_order_ordered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(default=0)),
                ('success_order_message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 1, 16, 979873, tzinfo=utc)),
        ),
    ]
