# Generated by Django 3.2.4 on 2021-07-05 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0020_auto_20210706_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='success_order_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 2, 14, 849670, tzinfo=utc)),
        ),
    ]
