# Generated by Django 3.2.4 on 2021-07-05 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0021_auto_20210706_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 22, 40, 929665, tzinfo=utc)),
        ),
    ]
