# Generated by Django 3.2.4 on 2021-07-08 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_shop', '0023_auto_20210707_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handler',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 16, 54, 28, 689657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
